// Auto-generated by frame vite plugin on first run. Edit freely from here.
import { createFileRoute } from "@tanstack/react-router";
import { handleFrameRequest } from "@/frame/server";
import { AppLayer } from "@/server/app-layer";
import { resolvers } from "@/server/resolvers/index.gen";

export const Route = createFileRoute("/api/frame")({
  server: {
    handlers: {
      POST: ({ request }) => handleFrameRequest(request, { resolvers, layer: AppLayer }),
    },
  },
});
