// Auto-generated by frame vite plugin. Do not edit — regenerated on dev start.
import type { ResolverMap } from "@/frame/server";
import { feed } from "./Query/feed";
import { postById } from "./Query/postById";
import { addComment } from "./Mutation/addComment";
import { User } from "./User";
import { Comment } from "./Comment";
import { Post } from "./Post";

export const resolvers: ResolverMap = {
  Query: { feed, postById },
  Mutation: { addComment },
  User,
  Comment,
  Post,
};
