import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { runnerImport } from "vite";
import type { Plugin, ResolvedConfig } from "vite";
import type { FieldDef, FrameType } from "./core/type";
import type { Query } from "./core/query";
import type { Mutation } from "./core/mutation";

export interface FramePluginOptions {
  /** Path to the API route file. Defaults to src/routes/api/frame.ts. */
  readonly apiRoutePath?: string;
  /** Schema barrel file. Defaults to src/server/schema/index.ts. */
  readonly schemaEntry?: string;
  /** Where resolver skeletons get written. Defaults to src/server/resolvers. */
  readonly resolversDir?: string;
  /** Module path for query imports (used in skeleton imports). Defaults to @/server/schema/queries. */
  readonly queriesModule?: string;
  /** Module path for mutation imports (used in skeleton imports). Defaults to @/server/schema/mutations. */
  readonly mutationsModule?: string;
  /** Module path for type imports (used in skeleton imports). Defaults to @/server/schema/types. */
  readonly typesModule?: string;
}

type AnyFrameType = FrameType<string, Record<string, FieldDef>>;
type AnyQuery = Query<string, unknown, AnyFrameType, boolean>;
type AnyMutation = Mutation<string, unknown, AnyFrameType>;

const API_ROUTE_TEMPLATE = `// Auto-generated by frame vite plugin on first run. Edit freely from here.
import { createFileRoute } from "@tanstack/react-router";
import { handleFrameRequest } from "@/frame/server";
import { AppLayer } from "@/server/app-layer";
import { resolvers } from "@/server/resolvers/index.gen";

export const Route = createFileRoute("/api/frame")({
  server: {
    handlers: {
      POST: ({ request }) =>
        handleFrameRequest(request, { resolvers, layer: AppLayer }),
    },
  },
});
`;

const queryConstName = (queryName: string): string => `${queryName}Query`;

const queryResolverSkeleton = (queryName: string, queriesModule: string): string => {
  const constName = queryConstName(queryName);
  return `import { Effect } from "effect";
import { defineQuery } from "@/frame/server";
import { ${constName} } from "${queriesModule}";

export const ${queryName} = defineQuery(${constName}, ({ input: _input }) =>
  Effect.gen(function* () {
    // TODO: implement ${queryName}
    return yield* Effect.fail(new Error("Not implemented: ${queryName}"));
  }),
);
`;
};

interface ResolverFieldInfo {
  readonly name: string;
  readonly kind: "ref" | "list" | "connection";
  readonly hasArgs: boolean;
}

const typeResolverSkeleton = (
  typeName: string,
  fields: readonly ResolverFieldInfo[],
  typesModule: string,
): string => {
  if (fields.length === 0) {
    return `import { defineType } from "@/frame/server";
import { ${typeName} as ${typeName}Type } from "${typesModule}";

export const ${typeName} = defineType(${typeName}Type)({});
`;
  }

  const fieldEntries = fields
    .map((f) => {
      // Bind unused params with `_` prefix so they don't trigger lint.
      const params =
        f.kind === "connection"
          ? f.hasArgs
            ? "{ parent: _parent, args: _args, after: _after, first: _first }"
            : "{ parent: _parent, after: _after, first: _first }"
          : f.hasArgs
            ? "{ parent: _parent, args: _args }"
            : "{ parent: _parent }";

      return `  ${f.name}: (${params}) =>
    Effect.gen(function* () {
      // TODO: implement ${typeName}.${f.name}
      return yield* Effect.fail(new Error("Not implemented: ${typeName}.${f.name}"));
    }),`;
    })
    .join("\n");
  return `import { Effect } from "effect";
import { defineType } from "@/frame/server";
import { ${typeName} as ${typeName}Type } from "${typesModule}";

export const ${typeName} = defineType(${typeName}Type)({
${fieldEntries}
});
`;
};

const mutationConstName = (name: string): string => `${name}Mutation`;

const mutationResolverSkeleton = (name: string, mutationsModule: string): string => {
  const constName = mutationConstName(name);
  return `import { Effect } from "effect";
import { defineMutation } from "@/frame/server";
import { ${constName} } from "${mutationsModule}";

export const ${name} = defineMutation(${constName}, ({ input: _input }) =>
  Effect.gen(function* () {
    // TODO: implement ${name}
    return yield* Effect.fail(new Error("Not implemented: ${name}"));
  }),
);
`;
};

const barrelContent = (
  queryNames: readonly string[],
  mutationNames: readonly string[],
  typeNames: readonly string[],
): string => {
  const queryImports = queryNames.map((q) => `import { ${q} } from "./Query/${q}";`).join("\n");
  const mutImports = mutationNames.map((m) => `import { ${m} } from "./Mutation/${m}";`).join("\n");
  const typeImports = typeNames.map((t) => `import { ${t} } from "./${t}";`).join("\n");
  const queryEntries = queryNames.join(", ");
  const mutEntries = mutationNames.join(", ");
  const typeEntries = typeNames.join(",\n  ");

  return `// Auto-generated by frame vite plugin. Do not edit — regenerated on dev start.
import type { ResolverMap } from "@/frame/server";
${queryImports}
${mutImports}
${typeImports}

export const resolvers: ResolverMap = {
  Query: { ${queryEntries} },${mutationNames.length ? `\n  Mutation: { ${mutEntries} },` : ""}${typeNames.length ? `\n  ${typeEntries},` : ""}
};
`;
};

const writeIfMissing = (filePath: string, content: string): boolean => {
  if (existsSync(filePath)) return false;
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, "utf8");
  return true;
};

const writeAlways = (filePath: string, content: string): void => {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, "utf8");
};

const isFrameType = (v: unknown): v is AnyFrameType =>
  typeof v === "object" && v !== null && (v as { __frame?: unknown }).__frame === "type";

const isFrameQuery = (v: unknown): v is AnyQuery =>
  typeof v === "object" && v !== null && (v as { __frame?: unknown }).__frame === "query";

const isFrameMutation = (v: unknown): v is AnyMutation =>
  typeof v === "object" && v !== null && (v as { __frame?: unknown }).__frame === "mutation";

const generateResolverSkeletons = async (
  config: ResolvedConfig,
  opts: Required<Omit<FramePluginOptions, "apiRoutePath">>,
): Promise<void> => {
  const root = config.root;
  const schemaPath = resolve(root, opts.schemaEntry);

  try {
    const { module } = await runnerImport<Record<string, unknown>>(schemaPath, {
      resolve: {
        alias: [
          { find: /^@\/(.*)$/, replacement: resolve(root, "src") + "/$1" },
          { find: /^#\/(.*)$/, replacement: resolve(root, "src") + "/$1" },
        ],
      },
    });

    const types: AnyFrameType[] = [];
    const queries: AnyQuery[] = [];
    const mutations: AnyMutation[] = [];
    for (const v of Object.values(module)) {
      if (isFrameType(v)) types.push(v);
      else if (isFrameQuery(v)) queries.push(v);
      else if (isFrameMutation(v)) mutations.push(v);
    }

    const resolversDir = resolve(root, opts.resolversDir);
    const queryNames: string[] = [];
    const mutationNames: string[] = [];
    const typeNames: string[] = [];

    for (const q of queries) {
      queryNames.push(q.name);
      const target = resolve(resolversDir, "Query", `${q.name}.ts`);
      writeIfMissing(target, queryResolverSkeleton(q.name, opts.queriesModule));
    }

    for (const m of mutations) {
      mutationNames.push(m.name);
      const target = resolve(resolversDir, "Mutation", `${m.name}.ts`);
      writeIfMissing(target, mutationResolverSkeleton(m.name, opts.mutationsModule));
    }

    for (const t of types) {
      // Transient (payload) types are not normalized and don't get type resolvers.
      if (t.transient) continue;
      const resolverFields: ResolverFieldInfo[] = [];
      for (const [name, def] of Object.entries(t.fields) as Array<[string, FieldDef]>) {
        if (def.kind === "scalar") continue;
        const hasArgs = "args" in def && def.args !== undefined;
        // A field needs a resolver if it has args, is a list, or is a connection.
        if (def.kind === "list" || def.kind === "connection" || hasArgs) {
          resolverFields.push({ name, kind: def.kind, hasArgs });
        }
      }
      typeNames.push(t.name);
      const target = resolve(resolversDir, `${t.name}.ts`);
      writeIfMissing(target, typeResolverSkeleton(t.name, resolverFields, opts.typesModule));
    }

    writeAlways(
      resolve(resolversDir, "index.gen.ts"),
      barrelContent(queryNames, mutationNames, typeNames),
    );

    config.logger.info(
      `[frame] generated ${queryNames.length} query, ${mutationNames.length} mutation, ${typeNames.length} type resolver skeleton(s)`,
    );
  } catch (err) {
    config.logger.warn(`[frame] could not generate resolver skeletons: ${(err as Error).message}`);
  }
};

export const frame = (options: FramePluginOptions = {}): Plugin => {
  const opts = {
    apiRoutePath: options.apiRoutePath ?? "src/routes/api/frame.ts",
    schemaEntry: options.schemaEntry ?? "src/server/schema/index.ts",
    resolversDir: options.resolversDir ?? "src/server/resolvers",
    queriesModule: options.queriesModule ?? "@/server/schema/queries",
    mutationsModule: options.mutationsModule ?? "@/server/schema/mutations",
    typesModule: options.typesModule ?? "@/server/schema/types",
  };

  return {
    name: "frame",
    configResolved(config) {
      const target = resolve(config.root, opts.apiRoutePath);
      writeIfMissing(target, API_ROUTE_TEMPLATE);

      void generateResolverSkeletons(config, {
        schemaEntry: opts.schemaEntry,
        resolversDir: opts.resolversDir,
        queriesModule: opts.queriesModule,
        mutationsModule: opts.mutationsModule,
        typesModule: opts.typesModule,
      });
    },
  };
};

export default frame;
